# Welcome to Jekyll!

# Website settings
title: "bblss123's Archive"
description: "bblss123's blog,use Jekyll and github pages."
keywords: "bblss123,Jalpc,blog,Jekyll,github,gh-pages"
baseurl: "/"
url: "http://bblss123.github.com"
url: "http://127.0.0.1:4000"

# blog img path
#img_path: 'http://www.jack003.com/static/img/blog'

# author
author:
  name: 'bblss123'
  first_name: 'Shen'
  last_name: 'Dylan'
  email: 'bblss123@outlook.com'
  facebook_username: 'bblss123'
  github_username: 'bblss123'
  head_img: 'static/img/landing/bblss123.png'

# social link
me:
  first_name: 'me'
  description: '蒟蒻'
  link: 'http://blog.csdn.net/bblss123'
  email: 'bblss123@outlook.com'
unicornt:
  first_name: 'unicornt'
  last_name: ''
  description: 'orz'
  link: 'http://unicornt.ml'
  email: 'unicornt@outlook.com'
KyleYoung:
  first_name: 'KyleYoung'
  description: 'orz'
  link: 'http://kyleyoung-ymj.github.io'
  email: 'kyleyoung-ymj@163.com'
ShinFeb:
  first_name: 'ShinFeb'
  last_name: ''
  description: 'orz'
  link: 'http://ShinFeb.logdowm.com'
  email: 'lyons0429@qq.com'

# landing page
landing:
  home: 'Home'
  about: 'About'
  career: 'Career'
  skills: 'Skills'
#  projects: 'Project'
  blog: 'Blog'
  link: 'Link'

# my projects
#project:
#  saplatform:
#    name: 'Saplatform'
#    url: '/Jack614/saplatform'
#    img: 'static/img/landing/saplatform.png'
#  jalpc:
#    name: 'Jalpc'
#    url: '/Jack614/jalpc_jekyll_theme'
#    img: 'static/img/landing/jekyll.png'
#  angularjs:
#    name: 'Jalpc-A'
#    url: '/Jack614/Jalpc-A'
#    img: 'static/img/landing/angularjs.png'
#  Rsser:
#    name: 'Rsser'
#    url: '/Jack614/Rsser'
#    img: 'static/img/landing/rsser.png'

# blog index
index:
  home: 'Home'
  python: 'Python'
  linux: 'Linux'
  html: 'HTML'
  database: 'Database'
  mac: 'Mac'
  life: 'Life'

# donate
# donate:
#   wechat: 'static/img/pay/wechat.png'
#   alipay: 'static/img/pay/alipay.png'

# comment
changyan:
  # appid: cysfY7ULn
  # conf: prod_861928934cecb7a18e15bedaed9dae29
disqus:
  name: jalpc
  public_key: tj2MPaNlHMONwTH5bGDNSXyaBpW7q282MeUzh5CwcjJerNhK8Kxk3aWo7IckzTX7

# share
bshare:
  uuid: 513f778e-a8f7-4c20-9ec2-d29cc2328d75

# baidu analytics
ba:
  uuid: 317acca9ef9255b934e46371e471431d

# google analytics
ga:
  id: UA-73784599-1

# Build settings
encoding: "utf-8"

# other settings
highlighter: rouge
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
